DB-project-1/backstage/views/analysis.py
from flask import render_template, Blueprint
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user
from link import *
from api.sql import Analysis

analysis = Blueprint('analysis', __name__, template_folder='../templates')

@analysis.route('/dashboard')
@login_required
def dashboard():
    revenue = []
    dataa = []
    care_revenue = []
    care_count = []

    for i in range(1,13):
        row = Analysis.month_price(i)

        if not row:
            revenue.append(0)
        else:
            for j in row:
                revenue.append(j[1])
        
        row = Analysis.month_count(i)
        
        if not row:
            dataa.append(0)
        else:
            for k in row:
                dataa.append(k[1])

        row = Analysis.month_cprice(i)

        if not row:
            care_revenue.append(0)
        else:
            for l in row:
                care_revenue.append(l[1])
        
        row = Analysis.month_ccount(i)
        
        if not row:
            care_count.append(0)
        else:
            for m in row:
                care_count.append(m[1])



    row = Analysis.category_sale()
    datab = []
    for i in row:
        temp = {
            'value': i[0],
            'name': i[1]
        }
        datab.append(temp)


    #care_category
    row = Analysis.category_care()
    care_category = []
    for i in row:
        temp = {
            'value': i[0],
            'name': i[1]
        }
        care_category.append(temp)

    
    row = Analysis.member_sale()
    
    datac = []
    nameList = []
    counter = 0
    
    for i in row:
        counter = counter + 1
        datac.append(i[0])
    for j in row:
        nameList.append(j[2])
    
    counter = counter - 1
    
    row = Analysis.member_sale_count()
    countList = []
    
    for i in row:
        countList.append(i[0])




        
    return render_template('dashboard.html', counter = counter, revenue = revenue, dataa = dataa, care_revenue = care_revenue, care_count = care_count, datab = datab, care_category = care_category, datac = datac, nameList = nameList, countList = countList)

DB-project-1/backstage/views/manager.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user
from link import *
from api.sql import *
import imp, random, os, string
from werkzeug.utils import secure_filename
from flask import current_app

UPLOAD_FOLDER = 'static/product'
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg'])

manager = Blueprint('manager', __name__, template_folder='../templates')

def config():
    current_app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
    config = current_app.config['UPLOAD_FOLDER'] 
    return config

@manager.route('/', methods=['GET', 'POST'])
@login_required
def home():
    return redirect(url_for('manager.productManager'))

@manager.route('/productManager', methods=['GET', 'POST'])
@login_required
def productManager():
    if request.method == 'GET':
        if(current_user.role == 'user'):
            flash('No permission')
            return redirect(url_for('index'))
        
    if 'delete' in request.values:
        pid = request.values.get('delete')
        data = Record.delete_check(pid)
        
        if(data != None):
            flash('failed')
        else:
            data = Product.get_product(pid)
            Product.delete_product(pid)
    
    elif 'edit' in request.values:
        pid = request.values.get('edit')
        return redirect(url_for('manager.edit', pid=pid))
    
    book_data = book()
    return render_template('productManager.html', book_data = book_data, user=current_user.name)

def book():
    book_row = Product.get_all_product()
    book_data = []
    for i in book_row:
        book = {
            '商品編號': i[0],
            '商品名稱': i[1],
            '商品售價': i[2],
            '商品類別': i[3]
        }
        book_data.append(book)
    return book_data

@manager.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        data = ""
        while(data != None):
            number = str(random.randrange( 10000, 99999))
            en = random.choice(string.ascii_letters)
            pid = en + number
            data = Product.get_product(pid)

        name = request.values.get('name')
        price = request.values.get('price')
        category = request.values.get('category')
        description = request.values.get('description')

        if (len(name) < 1 or len(price) < 1):
            return redirect(url_for('manager.productManager'))
        
        Product.add_product(
            {'pid' : pid,
             'name' : name,
             'price' : price,
             'category' : category,
             'description':description
            }
        )

        return redirect(url_for('manager.productManager'))

    return render_template('productManager.html')

@manager.route('/edit', methods=['GET', 'POST'])
@login_required
def edit():
    if request.method == 'GET':
        if(current_user.role == 'user'):
            flash('No permission')
            return redirect(url_for('bookstore'))

    if request.method == 'POST':
        Product.update_product(
            {
            'name' : request.values.get('name'),
            'price' : request.values.get('price'),
            'category' : request.values.get('category'), 
            'description' : request.values.get('description'),
            'pid' : request.values.get('pid')
            }
        )
        
        return redirect(url_for('manager.productManager'))

    else:
        product = show_info()
        return render_template('edit.html', data=product)


def show_info():
    pid = request.args['pid']
    data = Product.get_product(pid)
    pname = data[1]
    price = data[2]
    category = data[3]
    description = data[4]

    product = {
        '商品編號': pid,
        '商品名稱': pname,
        '單價': price,
        '類別': category,
        '商品敘述': description
    }
    return product


@manager.route('/orderManager', methods=['GET', 'POST'])
@login_required
def orderManager():
    if request.method == 'POST':
        pass
    else:
        order_row = Order_List.get_order()
        order_data = []
        for i in order_row:
            order = {
                '訂單編號': i[0],
                '訂購人': i[1],
                '訂單總價': i[2],
                '訂單時間': i[3]
            }
            order_data.append(order)
            
        orderdetail_row = Order_List.get_orderdetail()
        order_detail = []

        for j in orderdetail_row:
            orderdetail = {
                '訂單編號': j[0],
                '商品名稱': j[1],
                '商品單價': j[2],
                '訂購數量': j[3]
            }
            order_detail.append(orderdetail)

    return render_template('orderManager.html', orderData = order_data, orderDetail = order_detail, user=current_user.name)

@manager.route('/careManager', methods=['GET', 'POST'])
@login_required
def careManager():
    if request.method == 'POST':
        pass
    else:
        care_row = Care.get_care()
        care_data = []
        for i in care_row:
            care = {
                '保養編號': i[0],
                '商品編號': i[1],
                '商品名稱':i[2],
                '保養費用': i[3],
                '送件時間': i[4],
                '取件時間':i[5],
                '會員編號':i[6]
            }
            care_data.append(care)
    return render_template('careManager.html', careData = care_data, user=current_user.name)

DB-project-1/backstage/templates/backstage.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link href="../static/offcanvas.css" rel="stylesheet">
    <link rel="icon" href="../static/img/shopping-bag.ico" type="image/x-icon">
    <script src="../static/offcanvas.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/5.1.2/echarts.min.js"
        integrity="sha512-ppWbHq6q2f7HAwS481w6qikuC0XEeBnmkRg6KWnWg3zSIbJwWWBgsCDMAxzSB7SVqXzWwSYQ2s8TSJKjnaikMg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <title> {% block title%}{% endblock title%} </title>
    {% endblock head %}
</head>

<style>
    main>.container {
        padding: 60px 15px 0;
    }

    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
</style>

<body class="bg-light">
    <nav class="navbar navbar-expand-lg fixed-top navbar-light" style="background-color:#101919;">
        <div class="container-fluid container-xxl">
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 256 256">
                <path fill="white"
                    d="m239.89 198.12l-14.26-120a16 16 0 0 0-16-14.12H176a48 48 0 0 0-96 0H46.33a16 16 0 0 0-16 14.12l-14.26 120A16 16 0 0 0 20 210.6a16.13 16.13 0 0 0 12 5.4h191.92a16.13 16.13 0 0 0 12.08-5.4a16 16 0 0 0 3.89-12.48ZM128 32a32 32 0 0 1 32 32H96a32 32 0 0 1 32-32ZM32 200L46.33 80H80v24a8 8 0 0 0 16 0V80h64v24a8 8 0 0 0 16 0V80h33.75l14.17 120Z" />
            </svg>
            <a class="navbar-brand" href="#" style="color: white;">&nbsp;SSPL 後台管理系統</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('manager.productManager') }}"
                            style="color: white;">商品管理</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('manager.orderManager') }}" style="color: white;">訂單管理</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('manager.careManager') }}" style="color: white;">保養管理</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('analysis.dashboard') }}" style="color: white;">資料分析</a>
                    </li>

                </ul>



                <ul class="navbar-nav me-3 mb-2 mb-lg-0">
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24">
                        <path fill="white"
                            d="m12 23l-3-3H5q-.825 0-1.413-.588T3 18V4q0-.825.588-1.413T5 2h14q.825 0 1.413.588T21 4v14q0 .825-.588 1.413T19 20h-4l-3 3Zm0-11q1.45 0 2.475-1.025T15.5 8.5q0-1.45-1.025-2.475T12 5q-1.45 0-2.475 1.025T8.5 8.5q0 1.45 1.025 2.475T12 12Zm0 8.2l2.2-2.2H19v-1.15q-1.35-1.325-3.138-2.087T12 14q-2.075 0-3.863.763T5 16.85V18h4.8l2.2 2.2Z" />
                    </svg>
                    <li style="color:white;list-style-type:none">管理者：{{user}}</li>
                </ul>
                <div class="d-flex">
                    <a href="{{ url_for('api.logout') }}"><button class="btn btn-outline-danger"
                            type="submit">登出系統</button></a>
                </div>
            </div>
        </div>
    </nav>
    <br /><br />
    {% block content %}
    {% endblock content %}
</body>

</html>

DB-project-1/backstage/templates/careManager.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}
<!-- website title -->
{% block title %} 保養管理 {% endblock title %}

{% block content %}
<!-- website content -->
{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}
  
<script language="javascript">

  alert('您沒有管理者權限喔！');


</script>
{% endif %}
{% endwith %}


<script>
    $(document).ready(function () {
        $("#keyword").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#care tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

<br />
<div class="d-flex justify-content-between container-xxl">
    <div class="d-flex col-sm-4">
        <span class="input-group-text" id="basic-addon1">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search"
                viewBox="0 0 16 16">
                <path
                    d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
            </svg>
        </span>
        <input class="form-control me-2" id="keyword" placeholder="搜尋保養" aria-label="Search">
    </div>
</div>

<br />

<div class="container-xxl">
    <table class="table table-bordered">
        <thead>
            <tr>
                <!-- <th width="10%">商品編號</th> -->
                <th>
                    <center>會員編號</center>
                </th>
                <th>
                    <center>商品編號</center>
                </th>
                <th>
                    <center>商品名稱</center>
                </th>
                <td>
                    <center>保養費用</center>
                </td>
                <th>
                    <center>送件時間</center>
                </th>
                <th>
                    <center>取件時間</center>
                </th>
            </tr>
        </thead>
        <tbody id="care">
        {% for i in careData %}
            <tr>
                <td>
                    <center>{{ i.會員編號 }}</center>
                </td>
                <td>
                    <center>{{ i.商品編號 }}</center>
                </td>
                <td>
                    <center>{{ i.商品名稱 }}</center>
                </td>
                <td>
                    <center>{{ i.保養費用 }}</center>
                </td>
                <td>
                    <center>{{ i.送件時間 }}</center>
                </td>
                <td>
                    <center>{{ i.取件時間 }}</center>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

DB-project-1/backstage/templates/edit.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}

{% endblock head %}

{% block title %}BookStore{% endblock title%}

{% block content%}


<br />
<div class="container-xl">
  <br />
  <form method="post" enctype=multipart/form-data action={{ url_for('manager.edit') }}>
    <table class="table table-bordered">
      <tr>
        <th>商品編號</th>
        <td><input class="form-control" type="text" value="{{ data.商品編號 }}" name="pid" readonly class="id_input"></td>
      </tr>
      <tr>
        <th>商品名稱</th>
        <td><input class="form-control" type="text" value="{{ data.商品名稱 }}" name="name" required></td>
      </tr>
      <tr>
        <th>單價</th>
        <td><input class="form-control" type="text" value="{{ data.單價 }}" name="price" required></td>
      </tr>
      <tr>
        <th>類別</th>
        <td>
          <select class="form-control" name="category">
            {% if data.類別 == 'CD' %}
            <option value="BAG">BAG</option>
            <option value="SHOES">SHOES</option>
            <option value="JEWELRY" selected>JEWELRY</option>
            {% elif data.類別 == 'DVD' %}
            <option value="BAG">BAG</option>
            <option value="SHOES" selected>SHOES</option>
            <option value="JEWELRY">JEWELRY</option>
            {% else %}
            <option value="BAG" selected>BAG</option>
            <option value="SHOES">SHOES</option>
            <option value="JEWELRY">JEWELRY</option>
            {% endif %}
          </select>
      </tr>
      <tr>
        <th>商品敘述</th>
        <td>
          <textarea class="form-control" name="description">{{ data.商品敘述 }}</textarea>
        </td>
      </tr>
      <!-- <tr>
        <th>商品圖片</th>
        <td>
          <input type="file" name="file" id="file-uploader" data-target="file-uploader"/>
        </td>
      </tr> -->
    </table>
    <center>
      <div class="option">
        <button class="btn btn-outline-success" type="submit">確定修改</button>
        <a href="{{ url_for('manager.productManager') }}"><button class="btn btn-outline-danger">回商品管理</button></a>
      </div>
    </center>

  </form>
</div>



{% endblock content%}

DB-project-1/backstage/templates/manager.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}BookStore{% endblock title%}

{% block content%}
<div class="btn_div">
  <h1 class="book_title left">31 Lab Book Store</h1>
  <a href="{{ url_for('analysis.dashboard') }}" title="資料分析"><img class="cart"
      src="{{ url_for('static', filename='./img/dashboard.png') }}"></a>
  <a href="{{ url_for('logout') }}" title="登出"><img class="logout"
      src="{{ url_for('static', filename='./img/logout.png') }}"></a>
</div>
<div class="btn_div">
  <p class="welcome">歡迎 , 管理者：{{user}}</p>
</div>
{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}

<script language="javascript">

  alert('您沒有使用者的權限喔！');

</script>

{% endif %}
{% endwith %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'faild' %}

<script language="javascript">

  alert('有使用者有使用到這筆資料，所以不能刪除');

</script>

{% endif %}
{% endwith %}

<div class="book_table">
  <form method='post' action={{ url_for('manager') }}>
    <table cellpadding="10" border='3'>
      <tr>
        <th>商品編號</th>
        <th>商品名稱</th>
        <th>商品售價</th>
        <th>商品類別</th>
        <th></th>
        <th></th>
      </tr>
      {% for book in book_data %}
      <tr>
        <td> {{ book.商品編號 }}</td>
        <td> {{ book.商品名稱 }}</td>
        <td> {{ book.商品售價 }}</td>
        <td> {{ book.商品類別 }}</td>
        <td>
          <button type="submit" value="{{book.商品編號}}" name="edit">修改
          </button>
        </td>
        <td>
          <button type="submit" value="{{book.商品編號}}" name="delete"
            onclick="return (confirm('你確定要刪除 \'{{ book.商品名稱 }}\' 嗎？'))">
            刪除
          </button>
        </td>
      </tr>
      {% endfor %}
    </table>
    <div class="book_table">
      <a href={{ url_for('add')}}><button value="new" name="new" type="button"> 上架新商品</button></a>
    </div>
  </form>

</div>

{% endblock content%}

DB-project-1/backstage/templates/productManager.html
{% extends "backstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %} 商品管理 {% endblock title %}

{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}

<script language="javascript">

    alert('您沒有使用者的權限喔！');

</script>


{% endif %}
{% endwith %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'failed' %}

<script language="javascript">

    alert('有使用者有使用到這筆資料，所以不能刪除');

</script>

{% endif %}
{% endwith %}

<script>
    $(document).ready(function () {
        $("#keyword").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#product tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>
&nbsp;
&nbsp;
<div class="d-flex justify-content-between container-xxl">
    <div class="d-flex col-sm-4">
        <span class="input-group-text" id="basic-addon1">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search"
                viewBox="0 0 16 16">
                <path
                    d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
            </svg>
        </span>
        <input class="form-control me-2" id="keyword" placeholder="搜尋商品" aria-label="Search">
    </div>
    <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
        新增商品
    </button>
</div>

<form method="post" enctype=multipart/form-data action={{ url_for('manager.add') }}>
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">新增商品</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="inputProductName" class="form-label">商品名稱</label>
                        <input type="text" class="form-control" id="inputProductName" name="name" required>
                    </div>
                    <div class="mb-3">
                        <label for="inputUnitPrice" class="form-label">商品單價</label>
                        <input type="number" class="form-control" id="inputUnitPrice" name="price" required>
                    </div>
                    <div class="mb-3">
                        <label for="inputProductCategory" class="form-label">商品種類</label>
                        <select id="inputProductCategory" class="form-select" name="category" required>
                            <option selected disabled value="">請選擇類型</option>
                            <option value="BAG">BAG</option>
                            <option value="SHOES">SHOES</option>
                            <option value="JEWELRY">JEWELRY</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="inputProductDesc" class="form-label">商品敘述</label>
                        <textarea class="form-control" id="inputProductDesc" name="description" required></textarea>
                    </div>
                    <!-- <div class="mb-3">
                        <label for="inputProductImg" class="form-label">商品圖片</label><br/>
                        <input type="file" name="file" id="file-uploader" data-target="file-uploader" required/>
                    </div> -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">取消</button>
                    <button type="submit" class="btn btn-success">確定新增</button>
                </div>
            </div>
        </div>
    </div>
</form>

<br />

<div class="container-xxl">

    <form method='post' action={{ url_for('manager.productManager') }}>
        <table id="manager" class="table table-bordered">
            <thead>
                <tr>
                    <th width="10%">
                        <center>商品編號</center>
                    </th>
                    <th width="20%">
                        <center>商品名稱</center>
                    </th>
                    <th width="15%">
                        <center>商品單價</center>
                    </th>
                    <th width="15%">
                        <center>商品類別</center>
                    </th>
                    <th colspan="2">
                        <center>資料操作</center>
                    </th>
                </tr>
            </thead>
            <tbody id="product">
                {% for i in book_data %}
                <tr>
                    <td>
                        <center>{{ i.商品編號 }}</center>
                    </td>
                    <td>
                        <center>{{ i.商品名稱 }}</center>
                    </td>
                    <td>
                        <center>{{ i.商品售價 }}</center>
                    </td>
                    <td>
                        <center>{{ i.商品類別 }}</center>
                    </td>
                    <td>
                        <center><button type="submit" value="{{i.商品編號}}" name="edit"
                                class="btn btn-success">編輯商品</button></center>
                    </td>
                    <td>
                        <center><button type="submit" value="{{i.商品編號}}" name="delete"
                                onclick="return (confirm('你確定要刪除 \'{{ i.商品名稱 }}\' 嗎？'))"
                                class="btn btn-danger">刪除商品</button></center>
                    </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </form>


</div>

<script>
    function have_product() {
        alert('有使用者有使用到這筆資料，所以不能刪除');
    }
</script>

{% endblock content %}