DB-project-1/bookstore/views/store.py
import re
from typing_extensions import Self
from flask import Flask, request, template_rendered, Blueprint
from flask import url_for, redirect, flash
from flask import render_template
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user
from datetime import datetime
from numpy import identity, product
import random, string
from sqlalchemy import null
from link import *
import math
from base64 import b64encode
from api.sql import Member, Order_List, Product, Record, Cart, Care

store = Blueprint('bookstore', __name__, template_folder='../templates')

@store.route('/', methods=['GET', 'POST'])
@login_required
def bookstore():
    result = Product.count()
    count = math.ceil(result[0]/9)
    flag = 0
    
    if request.method == 'GET':
        if(current_user.role == 'manager'):
            flash('No permission')
            return redirect(url_for('manager.home'))

    if 'keyword' in request.args and 'page' in request.args:
        total = 0
        single = 1
        page = int(request.args['page'])
        start = (page - 1) * 9
        end = page * 9
        search = request.values.get('keyword')
        keyword = search
        
        cursor.prepare('SELECT * FROM PRODUCT WHERE PNAME LIKE :search')
        cursor.execute(None, {'search': '%' + keyword + '%'})
        book_row = cursor.fetchall()
        book_data = []
        final_data = []
        
        for i in book_row:
            book = {
                '商品編號': i[0],
                '商品名稱': i[1],
                '商品價格': i[2]
            }
            book_data.append(book)
            total = total + 1
        
        if(len(book_data) < end):
            end = len(book_data)
            flag = 1
            
        for j in range(start, end):
            final_data.append(book_data[j])
            
        count = math.ceil(total/9)
        
        return render_template('bookstore.html', single=single, keyword=search, book_data=book_data, user=current_user.name, page=1, flag=flag, count=count)    

    
    elif 'pid' in request.args:
        pid = request.args['pid']
        data = Product.get_product(pid)
        
        pname = data[1]
        price = data[2]
        category = data[3]
        description = data[4]
        image = data[1]+'.jpg'
        
        product = {
            '商品編號': pid,
            '商品名稱': pname,
            '單價': price,
            '類別': category,
            '商品敘述': description,
            '商品圖片': image
        }

        return render_template('product.html', data = product, user=current_user.name)
    
    elif 'page' in request.args:
        page = int(request.args['page'])
        start = (page - 1) * 9
        end = page * 9
        
        book_row = Product.get_all_product()
        book_data = []
        final_data = []
        
        for i in book_row:
            book = {
                '商品編號': i[0],
                '商品名稱': i[1],
                '商品價格': i[2]
            }
            book_data.append(book)
            
        if(len(book_data) < end):
            end = len(book_data)
            flag = 1
            
        for j in range(start, end):
            final_data.append(book_data[j])
        
        return render_template('bookstore.html', book_data=final_data, user=current_user.name, page=page, flag=flag, count=count)    
    
    elif 'keyword' in request.args:
        single = 1
        search = request.values.get('keyword')
        keyword = search
        cursor.prepare('SELECT * FROM PRODUCT WHERE PNAME LIKE :search')
        cursor.execute(None, {'search': '%' + keyword + '%'})
        book_row = cursor.fetchall()
        book_data = []
        total = 0
        
        for i in book_row:
            book = {
                '商品編號': i[0],
                '商品名稱': i[1],
                '商品價格': i[2]
            }

            book_data.append(book)
            total = total + 1
            
        if(len(book_data) < 9):
            flag = 1
        
        count = math.ceil(total/9)    
        
        return render_template('bookstore.html', keyword=search, single=single, book_data=book_data, user=current_user.name, page=1, flag=flag, count=count)    
    
    else:
        book_row = Product.get_all_product()
        book_data = []
        temp = 0
        for i in book_row:
            book = {
                '商品編號': i[0],
                '商品名稱': i[1],
                '商品價格': i[2],
            }
            if len(book_data) < 9:
                book_data.append(book)
        
        return render_template('bookstore.html', book_data=book_data, user=current_user.name, page=1, flag=flag, count=count)

# 會員購物車
@store.route('/cart', methods=['GET', 'POST'])
@login_required # 使用者登入後才可以看
def cart():
    request
    # 以防管理者誤闖
    if request.method == 'GET':
        if( current_user.role == 'manager'):
            flash('No permission')
            return redirect(url_for('manager.home'))

    # 回傳有 pid 代表要 加商品
    if request.method == 'POST':
        
        if "pid" in request.form :
            data = Cart.get_cart(current_user.id)
            
            
            if( data == None): #假如購物車裡面沒有他的資料
                time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                Cart.add_cart(time, current_user.id) # 幫他加一台購物車
                data = Cart.get_cart(current_user.id) 
                
            tno = data[2] # 取得交易編號
            pid = request.values.get('pid') # 使用者想要購買的東西
            # 檢查購物車裡面有沒有商品
            product = Record.check_product(pid, tno)
            # 取得商品價錢
            price = Product.get_product(pid)[2]

            # 如果購物車裡面沒有的話 把他加一個進去
            if(product == None):
                Record.add_product( {'id': tno, 'tno':pid, 'price':price, 'total':price} )
            else:
                # 假如購物車裡面有的話，就多加一個進去
                amount = Record.get_amount(tno, pid)
                total = (amount+1)*int(price)
                Record.update_product({'amount':amount+1, 'tno':tno , 'pid':pid, 'total':total})

        elif "delete" in request.form :
            pid = request.values.get('delete')
            tno = Cart.get_cart(current_user.id)[2]
            
            Member.delete_product(tno, pid)
            product_data = only_cart()
        
        elif "user_edit" in request.form:
            change_order()  
            return redirect(url_for('bookstore.bookstore'))
        
        elif "buy" in request.form:
            change_order()
            return redirect(url_for('bookstore.order'))

        elif "order" in request.form:
            tno = Cart.get_cart(current_user.id)[2]
            total = Record.get_total_money(tno)
            Cart.clear_cart(current_user.id)

            time = str(datetime.now().strftime('%Y/%m/%d %H:%M:%S'))
            format = 'yyyy/mm/dd hh24:mi:ss'
            Order_List.add_order( {'mid': current_user.id, 'time':time, 'total':total, 'format':format, 'tno':tno} )

            return render_template('complete.html', user=current_user.name)

    product_data = only_cart()
    
    if product_data == 0:
        return render_template('empty.html', user=current_user.name)
    else:
        return render_template('cart.html', data=product_data, user=current_user.name)

@store.route('/order')
def order():
    data = Cart.get_cart(current_user.id)
    tno = data[2]

    product_row = Record.get_record(tno)
    product_data = []

    for i in product_row:
        pname = Product.get_name(i[1])
        product = {
            '商品編號': i[1],
            '商品名稱': pname,
            '商品價格': i[3],
            '數量': i[2]
        }
        product_data.append(product)
    
    total = Record.get_total(tno)[0]

    return render_template('order.html', data=product_data, total=total, user=current_user.name)

@store.route('/orderlist')
def orderlist():
    if "oid" in request.args :
        pass
    
    user_id = current_user.id

    data = Member.get_order(user_id)
    orderlist = []

    for i in data:
        temp = {
            '訂單編號': i[0],
            '訂單總價': i[3],
            '訂單時間': i[2]
        }
        orderlist.append(temp)
    
    orderdetail_row = Order_List.get_orderdetail()
    orderdetail = []

    for j in orderdetail_row:
        temp = {
            '訂單編號': j[0],
            '商品名稱': j[1],
            '商品單價': j[2],
            '訂購數量': j[3]
        }
        orderdetail.append(temp)


    return render_template('orderlist.html', data=orderlist, detail=orderdetail, user=current_user.name)

def change_order():
    data = Cart.get_cart(current_user.id)
    tno = data[2] # 使用者有購物車了，購物車的交易編號是什麼
    product_row = Record.get_record(data[2])

    for i in product_row:
        
        # i[0]：交易編號 / i[1]：商品編號 / i[2]：數量 / i[3]：價格
        if int(request.form[i[1]]) != i[2]:
            Record.update_product({
                'amount':request.form[i[1]],
                'pid':i[1],
                'tno':tno,
                'total':int(request.form[i[1]])*int(i[3])
            })
            print('change')

    return 0


def only_cart():
    
    count = Cart.check(current_user.id)

    if(count == None):
        return 0
    
    data = Cart.get_cart(current_user.id)
    tno = data[2]
    product_row = Record.get_record(tno)
    product_data = []

    for i in product_row:
        pid = i[1]
        pname = Product.get_name(i[1])
        price = i[3]
        amount = i[2]
        
        product = {
            '商品編號': pid,
            '商品名稱': pname,
            '商品價格': price,
            '數量': amount
        }
        product_data.append(product)
    
    return product_data



DB-project-1/bookstore/templates/bookstore.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}商品列表{% endblock title%}

{% block content%}
<br />

{% with messages = get_flashed_messages() %}
{% if messages %}

<script language="javascript">

  alert('您沒有管理員的權限喔！');

</script>

{% endif %}
{% endwith %}

<div class="book_table container-xxl">

  <form class="d-flex col-sm-4" action="{{ url_for('bookstore.bookstore', keyword=1) }}">
    <div class="input-group">
      <span class="input-group-text" id="basic-addon1">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search"
          viewBox="0 0 16 16">
          <path
            d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
        </svg>
      </span>
      <input name='keyword' class="form-control me-2" type="search" placeholder="搜尋商品" aria-label="Search">
    </div>
  </form><br />
  <form method="post" action={{ url_for('bookstore.cart') }}>


    {% for book in book_data %}
    {% if loop.index % 3 == 1 %}
    <div class="row">
      {% endif %}

      <div class="col-sm-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{book.商品名稱}}</h5>
            <p class="card-text">${{book.商品價格}}</p>

            <a href="{{ url_for('bookstore.bookstore', pid=book.商品編號) }}" class="btn btn-outline-primary">查看商品資訊</a>
            <button class="btn btn-outline-success" type="submit" value="{{book.商品編號}}" name="pid">加入購物車</button>
          </div>
        </div>
      </div>

      {% if loop.index % 3 == 0 %}
    </div><br />
    {% endif %}

    {% endfor %}
    </table>
  </form>


  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if page == 1 %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% else %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('bookstore.bookstore', page=page-1) }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
      {% for i in range(1, count+1) %}
      {% if single == 1 %}
      <li class="page-item"><a class="page-link"
          href="{{ url_for('bookstore.bookstore', keyword=keyword, page=i) }}">{{i}}</a></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="{{ url_for('bookstore.bookstore', page=i) }}">{{i}}</a></li>
      {% endif %}
      {% endfor %}
      {% if flag == 1 %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% else %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('bookstore.bookstore', page=page+1) }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    </ul>
  </nav>



</div>

{% endblock content%}

DB-project-1/bookstore/templates/cart.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}購物車清單{% endblock title%}

{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages[0] == 'No permission' %}
  
<script language="javascript">
  alert('您沒有使用者的權限喔！');
</script>

{% endif %}
{% endwith %}

<br/>
<div class="container-xl">
  <br/>
  <form method="post" action={{ url_for('bookstore.cart') }}>
    <table class="table table-bordered">
      <tr>
        <th><center>商品編號</center></th>
        <th><center>商品名稱</center></th>
        <th><center>商品價格</center></th>
        <th><center>數量</center></th>
        <th><center>商品操作</center></th>
      </tr>
      {% for book in data %}
      <tr>
        <td> <center>{{ book.商品編號 }}</center></td>
        <td> <center>{{ book.商品名稱 }}</center></td>
        <td> <center>{{ book.商品價格 }}</center></td>
        <td width="20%">
          <center>
            <input class="form-control" type="number" onkeyup="value=value.replace(/[^\d]/g,'')" min="1" value="{{ book.數量 }}" name="{{ book.商品編號 }}">

          </center>
        </td>
        <td>
          <center>
            <button class="btn btn-danger" type="submit" value="{{book.商品編號}}" name="delete" onclick="return (confirm('你確定要刪除 \'{{ book.商品名稱 }}\' 嗎？'))">
              刪除
            </button>
          </center>
      </td>
      </tr>
      {% endfor %}
    </table>
    <center>
      <div class="option">
        <button class="btn btn-primary" type="submit" value="edit" name="user_edit" >繼續購物</button>
        <button class="btn btn-success" type="submit" value="edit" name="buy" >直接結帳</button>
      </div>
    </center>


  </form>

</div>

{% endblock content%}

DB-project-1/bookstore/templates/frontstage.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link href="../static/offcanvas.css" rel="stylesheet">
    <link rel="icon" href="../static/img/shopping-bag.ico" type="image/x-icon">
    <script src="../static/offcanvas.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>
    <title> {% block title%}{% endblock title%} </title>
    {% endblock head %}
</head>

<style>
    main>.container {
        padding: 60px 15px 0;
    }

    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
</style>

<body class="bg-light">
    <nav class="navbar navbar-expand-lg fixed-top navbar-light" style="background-color:#101919;">
        <div class="container-fluid container-xxl">
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 256 256">
                <path fill="white"
                    d="m239.89 198.12l-14.26-120a16 16 0 0 0-16-14.12H176a48 48 0 0 0-96 0H46.33a16 16 0 0 0-16 14.12l-14.26 120A16 16 0 0 0 20 210.6a16.13 16.13 0 0 0 12 5.4h191.92a16.13 16.13 0 0 0 12.08-5.4a16 16 0 0 0 3.89-12.48ZM128 32a32 32 0 0 1 32 32H96a32 32 0 0 1 32-32ZM32 200L46.33 80H80v24a8 8 0 0 0 16 0V80h64v24a8 8 0 0 0 16 0V80h33.75l14.17 120Z" />
            </svg>
            <a class="navbar-brand" href="#" style="color: white;">&nbsp;SSPL Boutique</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24">
                        <path fill="white"
                            d="M5.5 21c-.78 0-1.46-.45-1.79-1.1L1.1 10.44L1 10a1 1 0 0 1 1-1h4.58l4.6-6.57a.997.997 0 0 1 1.65.01L17.42 9H22a1 1 0 0 1 1 1l-.04.29l-2.67 9.61c-.33.65-1.01 1.1-1.79 1.1h-13M12 4.74L9 9h6l-3-4.26M12 13a2 2 0 0 0-2 2a2 2 0 0 0 2 2a2 2 0 0 0 2-2a2 2 0 0 0-2-2Z" />
                    </svg>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('bookstore.bookstore') }}" style="color: white;">商品導覽</a>
                    </li>
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24">
                        <path fill="white"
                            d="M7.3 21q-.95 0-1.625-.688T5 18.675V9.4L3.175 5H1V3h3.525l1.65 4H20.95q.575 0 .875.475t.025.975L19 14.025q1.275.2 2.138 1.175T22 17.5q0 1.45-1.012 2.475T18.524 21q-1.475 0-2.487-1.025T15.025 17.5q0-.5.125-.925t.35-.825l-3.275-.3l-3 4.5q-.325.5-.838.775T7.3 21Zm.025-2.025q.05 0 .225-.125l2.425-3.6q-1.225-.125-1.925-.587T7 13.7v5q0 .125.1.2t.225.075ZM18.5 19q.65 0 1.075-.438T20 17.5q0-.65-.425-1.075T18.5 16q-.625 0-1.063.425T17 17.5q0 .625.438 1.063T18.5 19Z" />
                    </svg>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('bookstore.cart') }}" style="color: white;">購物車</a>
                    </li>
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24">
                        <path fill="white"
                            d="m17 1.208l1.32 2.473L20.792 5L18.32 6.319L17.002 8.79L15.68 6.32L13.208 5l2.473-1.318L17 1.208ZM8 4.333l2.667 5l5 2.667l-5 2.666l-2.666 5l-2.667-5l-5-2.666l5-2.667l2.667-5Zm11.667 12l-1.666-3.125l-1.667 3.125L13.209 18l3.125 1.666l1.667 3.125l1.666-3.125L22.792 18l-3.125-1.667Z" />
                    </svg>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('bookstore.care') }}" style="color: white;">預約保養</a>
                    </li>
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24">
                        <path fill="white"
                            d="m17.275 18.125l-.425-.425q-.225-.225-.537-.225t-.538.225q-.225.225-.225.525t.225.525l.975.975q.225.225.525.225t.525-.225l2.425-2.375q.225-.225.225-.538t-.225-.537q-.225-.225-.538-.225t-.537.225l-1.875 1.85ZM7 9h10q.425 0 .713-.288T18 8q0-.425-.288-.713T17 7H7q-.425 0-.713.288T6 8q0 .425.288.713T7 9Zm11 14q-2.075 0-3.538-1.463T13 18q0-2.075 1.463-3.538T18 13q2.075 0 3.538 1.463T23 18q0 2.075-1.463 3.538T18 23ZM3 21.875V5q0-.825.588-1.413T5 3h14q.825 0 1.413.588T21 5v6.675q-.475-.225-.975-.375T19 11.075V5H5v14.05h6.075q.125.775.388 1.475t.687 1.325q-.125.025-.263-.038t-.237-.162l-.8-.8q-.15-.15-.35-.15t-.35.15l-.8.8q-.15.15-.35.15t-.35-.15l-.8-.8q-.15-.15-.35-.15t-.35.15l-.8.8q-.15.15-.35.15t-.35-.15l-.8-.8q-.15-.15-.35-.15t-.35.15l-.8.8l-.35.225ZM7 17h4.075q.075-.525.225-1.025t.375-.975H7q-.425 0-.713.288T6 16q0 .425.288.713T7 17Zm0-4h6.1q.95-.925 2.213-1.463T18 11H7q-.425 0-.713.288T6 12q0 .425.288.713T7 13Zm-2 6.05V5v14.05Z" />
                    </svg>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('bookstore.orderlist') }}" style="color: white;">歷史訂單</a>
                    </li>
                </ul>
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24">
                    <path fill="white"
                        d="m12 23l-3-3H5q-.825 0-1.413-.588T3 18V4q0-.825.588-1.413T5 2h14q.825 0 1.413.588T21 4v14q0 .825-.588 1.413T19 20h-4l-3 3Zm0-11q1.45 0 2.475-1.025T15.5 8.5q0-1.45-1.025-2.475T12 5q-1.45 0-2.475 1.025T8.5 8.5q0 1.45 1.025 2.475T12 12Zm0 8.2l2.2-2.2H19v-1.15q-1.35-1.325-3.138-2.087T12 14q-2.075 0-3.863.763T5 16.85V18h4.8l2.2 2.2Z" />
                </svg>

                <ul class="navbar-nav me-3 mb-2 mb-lg-0">
                    <li style="color:white;list-style-type:none">使用者：{{user}}</li>
                </ul>

                <a href="{{ url_for('api.logout') }}"><button class="btn btn-outline-danger"
                        type="submit">登出系統</button></a>
            </div>
        </div>
    </nav>
    <br /><br />
    {% block content %}
    {% endblock content %}
</body>

</html>

DB-project-1/bookstore/templates/order.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}BookStore{% endblock title%}

{% block content%}
<br/>
<div class="container-xl">
  <form method="post" action={{ url_for('bookstore.cart') }}>
    <table class="table table-bordered">
      <tr>
        <th><center>商品編號</center></th>
        <th><center>商品名稱</center></th>
        <th><center>商品價格</center></th>
        <th><center>數量</center></th>
      </tr>
      {% for book in data %}
      <tr>
        <td> <center>{{ book.商品編號 }}</center></td>
        <td> <center>{{ book.商品名稱 }}</center></td>
        <td> <center>{{ book.商品價格 }}</center></td>
        <td width="20%">
          <center>
            {{ book.數量 }}
          </center>
        </td>
      </tr>
      {% endfor %}
    </table>
    <div class="col align-self-end">
      
    </div>
    <div class="container-xxl" style="text-align: right;">
      <div class="row">
        <div class="col align-self-start">
 
        </div>
        <div class="col align-self-center">

        </div>
        <div class="col align-self-end">
          <b class="ml-50">訂單總價：{{ total }} 元</b>
        </div>
      </div>
    </div>

    
    <center> 
      <div class="option">
        <a href="{{ url_for('bookstore.cart') }}"><button class="btn btn-primary" type="submit" >回購物車</button></a>
        <button class="btn btn-success" type="submit" value="order" name="order">下訂單</button>
    </div>
    </center>

  </form>
</div>
{% endblock content%}

DB-project-1/bookstore/templates/orderlist.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}BookStore{% endblock title%}

{% block content %}
<!-- <form method="post" action="#"> -->
  {% for i in data %}
  <div class="modal fade" id="staticBackdrop{{i.訂單編號}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="staticBackdropLabel">訂單細項列表</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                  <div class="mb-3">
                    <table class="table table-bordered">
                      <tr>
                        <th><center>商品名稱</center></th>
                        <th><center>商品單價</center></th>
                        <th><center>訂購數量</center></th>
                      </tr>
                      
                      {% for j in detail %}
                      {% if j.訂單編號 == i.訂單編號 %}
                      <tr>
                        <td> <center>{{ j.商品名稱 }}</center></td>
                        <td> <center>{{ j.商品單價 }}</center></td>
                        <td> <center>{{ j.訂購數量 }}</center></td>
                      </tr>
                      {% endif %}
                      {% endfor %}
                    </table>
                  </div>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-outline-success" data-bs-dismiss="modal" style="width:30%;">回訂單</button>
              </div>
          </div>
      </div>
  </div>
  {% endfor %}
<!-- </form> -->



<br/>
<div class="container-xl">
  <form method="post" action={{ url_for('bookstore.orderlist') }}>
    <table class="table table-bordered">
      <tr>
        <th><center>訂單編號</center></th>
        <th><center>訂單總價</center></th>
        <th><center>訂單時間</center></th>
        <th><center>查看訂單</center></th>
      </tr>
      {% for i in data %}
      <tr>
        <td> <center>{{ i.訂單編號 }}</center></td>
        <td> <center>{{ i.訂單總價 }}</center></td>
        <td> <center>{{ i.訂單時間 }}</center></td>
        <td width="20%">
          <center>
            <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#staticBackdrop{{i.訂單編號}}">
              查看訂單細項
            </button>
          </center>
        </td>
      </tr>
      {% endfor %}
    </table>

  </form>
</div>

{% endblock content %}


DB-project-1/bookstore/templates/product.html
{% extends "frontstage.html" %}
{% block head %}
{{ super() }}
{% endblock head %}

{% block title %}BookStore{% endblock title%}

{% block content %}

{% set temp = 'img/' + data.商品圖片 %}

<br/>
<div class="row">
<div class="card" style="width: 20rem;margin-left:5%">
  <img src={{ url_for('static', filename = temp  ) }} class="card-img-top">
  <div class="card-body">
    <h5 class="card-title">{{ data.商品名稱 }}</h5>
    <p class="card-text"></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><b>商品類別</b>&nbsp;&nbsp;{{ data.類別 }}</li>
    <li class="list-group-item"><b>商品單價</b>&nbsp;&nbsp;{{ data.單價 }}</li>
  </ul>
  <div class="card-body">
    <a href="{{ url_for('bookstore.bookstore') }}" class="btn btn-outline-primary">回商品列表</a>
  </div>
</div>


<div class="col-sm-6">
  <form method="post" action={{ url_for('bookstore.cart') }}>
<div class="card" style="margin-top:10%">
  <h5 class="card-header">商品介紹</h5>
  <div class="card-body">
    <p class="card-text">
      {{data.商品敘述}}
    </p>
    <button class="btn btn-outline-success" type="submit" value="{{data.商品編號}}" name="pid">加入購物車</a>
  </div>
</div>
</form>
</div>


</div>


{% endblock content%}